AWSTemplateFormatVersion: "2010-09-09"
Description: Data Migration Setup Stack

Parameters:
  DataLakeBucketName:
    Type: String
    Description: Name of the S3 Data Lake bucket

Resources:
  DataLakeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DataLakeBucketName

  MigrationGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: migration_catalog_db
        Description: Glue catalog database for migration project

  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: data-migration-glue-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
  GlueS3AccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: glue-s3-access
      Roles:
        - Ref: GlueServiceRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::${DataLakeBucketName}

          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource:
              - !Sub arn:aws:s3:::${DataLakeBucketName}/*

  GlueLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws-glue/data-migration
      RetentionInDays: 14

  